### ISSUE TITLE
NaN being appended to method source

### ISSUE THREAD

**Issue by pehrlich** [sole/tween.js#175]
So this works:

```
  .to( { x: mesh.userData.position.x, y: mesh.userData.position.y, z: mesh.userData.position.z}, 700 )
```

This doesn't, but I wish it did:

```
  .to( mesh.userData.position, 700 )
```

However, this causes "NaN" to be appended to the position's constructor's source, causing breakage.  Position is a THREE.Vector3.

**Comment by sole** [comment]
Oops I hadn't seen this before.

Thanks for replying @dalisoft :)

Closing as non-issue
